### ISSUE TITLE
controls: 0 not working

### ISSUE THREAD

**Issue by dougdelabrida** [appleple/modal-video#10]
Hi guys, thanks for this amazing library.

I'm trying to set youtube controls to 0 by doing this:

``$(".js-modal-btn").modalVideo({youtube: {controls: 0}});``

Unfortunately the controls are still visible.

Is there any example in the docs about this?

**Comment by steelydylan** [comment]
Hi @dougdelabrida 
sorry It was a bug and I just fixed the bug :(
you can hide the controls with the same code now :)
https://github.com/appleple/modal-video/tree/master/js

**Comment by dougdelabrida** [comment]
Thanks.
