### ISSUE TITLE
Show popup on pageload

### ISSUE THREAD

**Issue by abhilashrajrs** [appleple/modal-video#12]
Hi

Is there a way to show the popup on pageload.

**Comment by bavillaloboso** [comment]
hi
 its very easy using a simple function in javascript 

`<p id="clickButton" class="btn btn-red js-video-btn" data-video-id='KnVJZzJ9TuU' >Open Video</p>


	
   
			<script>
			
window.onload = function() {
  
  // Trigger on load
  $("#clickButton").click();
  
  function display(msg) {
    var p = document.createElement('p');
    p.innerHTML = msg;
    document.body.appendChild(p);
  }
};	
			window.addEventListener('DOMContentLoaded',function(){	
				new ModalVideo(".js-video-btn");
			});
		
		
			
		
			
			
			
			</script>`

**Comment by ayafaheem** [comment]
@dysat  is there away to destroy ModalVideo ?

**Comment by steelydylan** [comment]
Hi @ayafaheem 
modal-video doesn't have such method to destroy modal-video
When do you want to destroy ModalVideo?

**Comment by uidev1116** [comment]
Closing due to no reply for a period of time,  please re-open if that PR would not cover this case.
