### ISSUE TITLE
How to play own video？

### ISSUE THREAD

**Issue by shouhuori** [appleple/modal-video#21]

**Comment by steelydylan** [comment]
@shouhuori 
Opps! I should have added that feature
I'll make the option for that soon and let you know :)

**Comment by steelydylan** [comment]
Hi @shouhuori 
I just published the new version 

From @2.4.0, you can specify the url directly like below

```html
<button class="js-video-button" data-channel="video" data-video-url="http://developer.a-blogcms.jp/themes/developer/movies/2.8.0.mp4">video</button>
```

**Comment by shouhuori** [comment]
So good! Thank you very much!
