### ISSUE TITLE
Custom YouTube arguments not functioning. 

### ISSUE THREAD

**Issue by brohlson** [appleple/modal-video#22]
Hey there, 

I'm passing my arguments to the init function like so:

    $(".js-modal-btn").modalVideo({
        controls:0,
        modestbranding: 1,
        byline: false
    });

Nothing's being reflected in the actual modal.  Anything wrong with what I'm doing here?

**Comment by steelydylan** [comment]
Hi @brohlson 
you have to wrap the options with youtube property like this.

```js
$(".js-modal-btn").modalVideo({
    youtube: {
      controls:0,
      modestbranding: 1,
      byline: false
    }
});
```

**Comment by brohlson** [comment]
@steelydylan Worked like a charm, thanks for the quick response!!
