### ISSUE TITLE
Dynamic channel using data attribute

### ISSUE THREAD

**Issue by kodeine** [appleple/modal-video#23]
Is it possible to inject the channel as well. I'm using this on a blog page and blogger can use vimeo or youtube. 
`<button class="js-modal-btn" data-video-id="202177974" data-video-channel="vimeo">Open Vimeo</button>`

**Comment by steelydylan** [comment]
Hi @kodeine 
You can already do that with the following code

```html
<button class="js-modal-btn" data-video-id="202177974" data-channel="vimeo">Open Vimeo</button>
```

**Comment by kodeine** [comment]
@steelydylan awsome, thanks. I did not see that in documentation or i over looked it.
