### ISSUE TITLE
Vimeo and Youtube not working now

### ISSUE THREAD

**Issue by joaquin74292** [appleple/modal-video#27]
I thought it was my mistake coding something wron but checking you're file on the .zip it didn't work too.

**Comment by ALinedDesign** [comment]
Me either. I get an error - An error occurred. Please try again later. - then click the x and the video works. Can see on a development page here https://www.walkonkunanyi.com.au/mountain-gems/

**Comment by steelydylan** [comment]
Hi @ joaquin74292 and @ALinedDesign 

The modal-video can only work under the localhost domain or the domains start with http/https

**Comment by uidev1116** [comment]
Closing due to no reply for a period of time,  please re-open if that PR would not cover this case.
