### ISSUE TITLE
change for compatibility with IE10

### ISSUE THREAD

**Issue by Colir** [appleple/modal-video#28]
Hi.
Thanks for this lib. it's working very well.
However, i suggest one change for make it working on IE10

Change the use of "dataset" by getting directly the attribute
`
var videoId = selector.dataset.videoId;
var channel = selector.dataset.channel || opt.channel;
var id = (0, _util.getUniqId)();
var videoUrl = selector.dataset.videoUrl || _this.getVideoUrl(opt, channel, videoId);
`

become

`
var videoId = selector.getAttribute('data-video-id');
var channel = selector.getAttribute('data-channel') || opt.channel  ;
var id = (0, _util.getUniqId)();
var videoUrl = selector.getAttribute('data-video-url') || _this.getVideoUrl(opt, channel, videoId);
`
 Thank you

**Comment by ThoDon** [comment]
Hello Colir, thanks for you fix as I had to support IE10 for this project :)

**Comment by uidev1116** [comment]
@Colir @ThoDon 

Sorry for the late reply.
I never support expired versions of IE (and other projects based on such versions) anymore, because I can't take enough  time to support them.

**Comment by ThoDon** [comment]
Yeah no worry mate, nearly four years later, we dropped IE10/11/Edge everywhere, there is no point maintaining for theses, cheers !

**Comment by uidev1116** [comment]
@ThoDon 

Thanks! Closing due to comments above.
