### ISSUE TITLE
Site does not work for me and download doesn't work

### ISSUE THREAD

**Issue by HeadStudios** [appleple/modal-video#38]
Just downloaded the zip from the website and when I open index.html in test folder the only thing that works is the .mp4 file link - Vimeo/Youtube broken. https://cl.ly/df87dd5915e2/Image%2525202019-09-25%252520at%25252010.10.37%252520PM.png 

Any idea why this happening? 

Thanks

**Comment by steelydylan** [comment]
Hi @HeadStudios 
You have to use it on the server or the localhost

**Comment by uidev1116** [comment]
Closing in favor of https://github.com/appleple/modal-video/issues/38#issuecomment-555307708, please re-open if that PR would not cover this case
