### ISSUE TITLE
Images?

### ISSUE THREAD

**Issue by feliperuizmendoza** [appleple/modal-video#4]
Hi there!

I'm using you plugin and it has worked well so far. I wonder if there's an easy way to pull an image instead of a video. I mean, that would be great!

Thanks,

Felipe

**Comment by steelydylan** [comment]
Hi @feliperuizmendoza 

I'm sorry but this plugin is not meant for image viewer
You may want to use the library below instead
https://github.com/appleple/SmartPhoto

It is touch compatible and really easy to use and no dependencies :)
