### ISSUE TITLE
$(...).modalVideo is not a function

### ISSUE THREAD

**Issue by umairkhan125** [appleple/modal-video#40]
Hi

I am intializing the modalvideo with all requirements but getting the error

$(...).modalVideo is not a function

**Comment by iMezied** [comment]
@umairkhan125 
import jquery-modal-video.min.js instead of modal-video.min.js

**Comment by firmstudio-kakirastern** [comment]
Thanks @iMezied I ran into the same problem too and now it works fine after importing the right file

**Comment by saifulp** [comment]
> modal

thanks @iMezied  its work fine. i have faced big problem with this issue.

**Comment by tJay11** [comment]
works but doesnt autoplay

**Comment by uidev1116** [comment]
Closing due to working fine.
