### ISSUE TITLE
More than 1 video 

### ISSUE THREAD

**Issue by burke15** [appleple/modal-video#5]
If there is more than one video on page, say 5 then you have to close the first video 5 times, the next,  4 times, then 3, then two and the last video closes on the first try.  How can you fix this?

**Comment by steelydylan** [comment]
Hi @burke15 :)

Regardless of the number of videos on one page, you can close video just on the first try, If you use our plugin correctly.
For your reference, this is the site using modal-video for many videos
http://chiyo-katsumasa.com/video/

Following is the only code you have to write.
`$(".js-modal-btn").modalVideo();`

**Comment by burke15** [comment]
Thank you Hori
