### ISSUE TITLE
Release to npm.

### ISSUE THREAD

**Issue by torounit** [appleple/modal-video#6]
Thank you for your work. 🥇 

Hosted only react-modal-video. 
https://www.npmjs.com/~appleple

Release at npm ?

**Comment by steelydylan** [comment]
Hi @torounit  :)
Currently, I'm working on the feature/npm branch below to make npm version of this.
https://github.com/appleple/modal-video/tree/feature/npm
From the new version, you can use our library something like below.

`
import ModalVideo from 'modal-video';
new ModalVideo('.js-modal-btn');
`

I'll tell you when I have done with it, I don't know when I can finish it tho...

**Comment by steelydylan** [comment]
Hi @torounit 

I just published it on npm

https://www.npmjs.com/package/modal-video

You can use this library like below

`
new ModalVideo('.js-modal-video');
`

**Comment by torounit** [comment]
👍
