### ISSUE TITLE
All modals for youtube displaying "This video is unavailable."

### ISSUE THREAD

**Issue by dtotheram** [appleple/modal-video#73]
Even on the demo site the modals don't seem to be working.
![2021 07 21 04 02 23PM--screenshot](https://user-images.githubusercontent.com/33231496/126552948-a4b64bb0-4c19-4f0b-985b-6c9229f4e552.png)

**Comment by obj63mc** [comment]
Troubleshooting this on a site, it appears that if you have the playlist variables in the embed url but are not loading a playlist it will error out.  So the defaults simply need to remove playlist, list and listType variables and then it will load.  Basically according to this - https://developers.google.com/youtube/player_parameters?hl=en you should either be providing a video id or playlist information not both.  There was also some deprecations late last year in terms of playlists and assuming that their final updates were pushed today.

**Comment by obj63mc** [comment]
To give an example - the URL that is generated for the embed is - 

https://www.youtube.com/embed/L61p2uyiMSo?autoplay=1&cc_load_policy=1&color=null&controls=1&disablekb=0&enablejsapi=0&end=null&fs=1&h1=null&iv_load_policy=1&list=null&listType=null&loop=0&modestbranding=null&mute=0&origin=null&playlist=null&playsinline=null&rel=0&showinfo=1&start=0&wmode=transparent&theme=dark&nocookie=false

which won't work but the following link will simply removing &list=null and &playlist=null

https://www.youtube.com/embed/L61p2uyiMSo?autoplay=1&cc_load_policy=1&color=null&controls=1&disablekb=0&enablejsapi=0&end=null&fs=1&h1=null&iv_load_policy=1&listType=null&loop=0&modestbranding=null&mute=0&origin=null&playsinline=null&rel=0&showinfo=1&start=0&wmode=transparent&theme=dark&nocookie=false

**Comment by eytanchen** [comment]
Thanks a lot!! You've just saved me hours of investigating.

**Comment by dtotheram** [comment]
Thanks so much, @obj63mc! 
I was wondering why the modals often show a playlist option in the embed but it was empty when I clicked it.

**Comment by OwenMelbz** [comment]
Anybody have any ideas when this is likely to be merged and released?

Thanks :)

**Comment by zietbukuel** [comment]
I'm having the exact same issue. I've tried to download the v2.4.4 tag but it doesn't seem to work. The js/ folder only contains files from v2.4.3, not the updated ones. I've also tried to build this myself, but I'm getting this error:

`error An unexpected error occurred: "https://registry.yarnpkg.com/electron/-/electron-1.8.0.tgz: Request failed \"404 Not Found\""`

And I can't continue anymore.

**Comment by thomasfrobieter** [comment]
https://github.com/appleple/modal-video/pull/74 Fixed this issue for me.

@zietbukuel The built JS & CSS files are also included in the repo, so just use this files (https://github.com/appleple/modal-video/archive/refs/heads/master.zip) till the next release?

**Comment by OwenMelbz** [comment]
> @zietbukuel

Any suggestions for the **easiest** way for users to do this if they're using a package manager such as yarn/npm etc and not just downloading files directly?

**Comment by zietbukuel** [comment]
@thomasfrobieter That's the first thing I did... take a look at this file: https://github.com/appleple/modal-video/blob/v2.4.4/js/jquery-modal-video.js it's verion 2.4.3 not 2.4.4.

**Comment by zietbukuel** [comment]
@thomasfrobieter thank you, now I see master contains v2.4.4

**Comment by ABooooo** [comment]
Thank you, it works!

**Comment by b7-afonso** [comment]
The error on the video still exists on the Demo page https://appleple.github.io/modal-video/

**Comment by eldorokhova** [comment]
I'm having the same issue, except my video url doesn't have any playlists in url, the generated link simply has the video id, but the video is unavailable. Any suggestions?

**Comment by stevethorson** [comment]
I am having this issue, but after reading through this thread, I switched from using jquery-modal-video.min.js to using jquery-modal-video.js, and that fixed it. Is there a problem with the minified version?

**Comment by stevethorson** [comment]
this is working for me now in version 2.4.6.

**Comment by uidev1116** [comment]
Closing in favor of #74. Thanks!
